services:
    nexmo.client.credentials.basic:
        public: false
        class: Nexmo\Client\Credentials\Basic
        arguments:
            - '%botjaeger_nexmo.api_key%'
            - '%botjaeger_nexmo.api_secret%'

    default_nexmo.client:
        public: true
        class: Nexmo\Client
        arguments:
            - '@nexmo.client.credentials.basic'

    botjaeger_nexmo.client:
        public: true
        class: Botjaeger\NexmoBundle\NexmoClient\NexmoClient
        arguments:
            - '@default_nexmo.client'
            - '%botjaeger_nexmo.api_brand%'
